import Head from 'next/head'
import Script from 'next/script'

import styles from '../styles/Home.module.scss'
import { useEffect, useRef, useState } from "react";
import { useRouter } from 'next/router'
import NET from "vanta/dist/vanta.net.min";
import * as THREE from "three";

import Nav from '../components/nav';
import Footer from '../components/footer';
import Change from '../components/change';
import ChangeTwo from '../components/changeTwo';



export default function Home() {
  const [isActive, setActive] = useState(false);

  const handleToggle = () => {
    setActive(!isActive);
  }

  const [vantaEffect, setVantaEffect] = useState(0);
  const vantaRef = useRef(null);
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(
        NET({
          el: vantaRef.current,
          THREE,
          color: 0xcc0063,
          backgroundColor: 0x161616,
          //maxDistance: 30.0,
          points: 20.00,
        })
      );
    }
    return () => {
      if (vantaEffect) {
        // vantaEffect.destory();
      }
    };
  }, [vantaEffect]);

  const router = useRouter()
  if(isActive) {
    setTimeout(() => {
      router.push('/work');
    }, 1000);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`} ref={vantaRef} >
        <div className={`${styles.changeTwo} ${isActive ? styles.changed : null}`}>
          <ChangeTwo/>
        </div>
        <div className={`${styles.change} ${isActive ? styles.changed : null}`} >
          <Change />
        </div>
        <Nav no='1'/>
        <div className={`${styles.hero} mons flex justCenter flexCol alignCenter`}>
          <h1 className={`${styles.title} flex`}>
            Design&nbsp;
            <span className={`${styles.rade}`} >
              Rade
            </span>
          </h1>
          <p className={`${styles.subtitle} noto`} >Design the future</p>
          <button className={`roboto flex alignCenter`} onClick={handleToggle}>
            Explore &nbsp;
            <span className={`flex`} >
              <svg width="51" height="24" viewBox="0 0 51 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M50.0607 13.0607C50.6464 12.4749 50.6464 11.5251 50.0607 10.9393L40.5147 1.3934C39.9289 0.807615 38.9792 0.807615 38.3934 1.3934C37.8076 1.97919 37.8076 2.92894 38.3934 3.51472L46.8787 12L38.3934 20.4853C37.8076 21.0711 37.8076 22.0208 38.3934 22.6066C38.9792 23.1924 39.9289 23.1924 40.5147 22.6066L50.0607 13.0607ZM-1.31134e-07 13.5L49 13.5L49 10.5L1.31134e-07 10.5L-1.31134e-07 13.5Z" fill="#161616"/>
              </svg>
            </span>
          </button>
        </div>
        <Footer/>
      </main>
    </div>
  )
}
