import Head from 'next/head'
import Nav from '../components/nav'

import works from '../styles/Work.module.scss';
import { useEffect, useRef, useState } from "react";
import Snowfall from 'react-snowfall';



// import { Controller, Scene } from 'react-scrollmagic';


export default function Work() {
    const [scroll, setScroll] = useState(false);
    const scroller = useRef();
    useEffect(() => {
        scroller.current.addEventListener("scroll", () => {
            const scrollCheck = window.scrollY < 1000;
            if (scrollCheck !== scroll) {
                setScroll(scrollCheck);
            }
        });
    });
    return (
        <div className={works.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* remove style later */}
            <main className={`${works.main}`} ref={scroller}>
                <Nav no='2'/>
                <div className={`${works.content}`} >
                    <div className={`${works.myWork} ${works.workleft}`} ></div>
                    <div className={`${works.myWork} ${works.workright}`} ></div>
                    <div className={`${works.myWork} ${works.workleft}`} ></div>
                    <div className={`${works.myWork} ${works.workright}`} ></div>
                    <button className={`${works.abtBtn}`} >About us</button>
                </div>
                {/* <Controller>
                    <Scene classToggle={`${works.show}`}  duration={200} triggerElement={`#ship`} indicators={true}>  */}
                <div className={`${works.ship} ${scroll ? works.rotate : null}`} id='ship'>
                    <svg width="371" height="328" viewBox="0 0 371 328" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect x="145" y="230" width="81" height="98" fill="url(#paint0_linear_16_143)"/>
                        <path d="M369.739 190.957L328.618 163.694V147.346V146.732H328.003H320.633H320.018V147.346V157.993L278.25 130.301V114.177V113.563H277.636H270.265H269.651V114.177V124.599L226.535 96.0135L225.424 82.1876L225.414 82.0717L225.363 81.9672L186.666 2.73045L186.131 1.63486L185.569 2.71689L144.415 81.9537L144.357 82.0663L144.348 82.193L143.259 97.4407L101.349 125.041V114.177V113.563H100.735H93.3643H92.7501V114.177V130.705L50.9818 158.213V147.346V146.732H50.3676H42.9967H42.3825V147.346V163.876L1.26277 190.957H1.22852H0.614277V191.571V218.598V219.212H1.22852H14.7418H15.356V218.598V210.613H135.175L134.52 219.782L134.501 220.051L134.685 220.247L174.507 262.517L185.513 314.546H186.715L197.802 262.135L236.32 220.242L236.501 220.044L236.48 219.777L235.743 210.613H355.644V218.598V219.212H356.258H369.772H370.386V218.598V191.571V190.957H369.772H369.739Z" fill="#161616" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M204.541 66.8808C204.541 67.3193 204.43 67.6546 204.24 67.9261C204.045 68.2039 203.74 68.4532 203.296 68.6684C202.389 69.1076 201.02 69.3496 199.235 69.457C197.464 69.5636 195.36 69.5349 193.023 69.4782C192.555 69.4669 192.078 69.4544 191.593 69.4418C189.664 69.3914 187.609 69.3378 185.5 69.3378C183.391 69.3378 181.336 69.3914 179.407 69.4418C178.922 69.4544 178.445 69.4669 177.977 69.4782C175.64 69.5349 173.536 69.5636 171.765 69.457C169.98 69.3496 168.611 69.1076 167.704 68.6684C167.26 68.4532 166.955 68.2039 166.76 67.9261C166.57 67.6546 166.459 67.3193 166.459 66.8808C166.459 65.9715 166.941 64.7828 167.928 63.4699C168.903 62.1723 170.324 60.8178 172.081 59.5878C175.597 57.1261 180.39 55.2103 185.5 55.2103C190.61 55.2103 195.403 57.1261 198.919 59.5878C200.676 60.8178 202.097 62.1723 203.072 63.4699C204.059 64.7828 204.541 65.9715 204.541 66.8808Z" fill="#E61E72" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M225.426 82.2368L236.482 219.826" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M144.346 82.2368L134.518 219.826" stroke="#B9165B" strokeWidth="1.22848"/>
                        <line x1="15.3559" y1="190.957" x2="15.3559" y2="210.613" stroke="#B9165B" strokeWidth="1.22848"/>
                        <line x1="355.644" y1="190.957" x2="355.644" y2="210.613" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M3.92061e-05 190.957L136.975 190.957" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M234.025 190.957H371" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M225.426 82.2368L186.114 120.934L144.346 82.2368" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M186.114 120.934L174.444 262.209" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M186.112 120.881L197.785 262.209" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M174.444 262.209L186.114 198.328" stroke="#B9165B" strokeWidth="1.22848"/>
                        <path d="M197.785 262.325L186.114 198.328" stroke="#B9165B" strokeWidth="1.22848"/>
                        <defs>
                        <linearGradient id="paint0_linear_16_143" x1="185.5" y1="230" x2="185.5" y2="328" gradientUnits="userSpaceOnUse">
                        <stop stopColor="#B9165B"/>
                        <stop offset="1" stopColor="#FF00C7" stopOpacity="0"/>
                        <stop offset="1" stopColor="#B9165B" stopOpacity="0"/>
                        </linearGradient>
                        </defs>
                    </svg>
                </div>
                <div className={`${works.stars}`} >
                    <Snowfall color='#E51E72' wind={[0, 0]} radius={[1, 2]} speed={[0.5, 1]} snowflakeCount={150}/>
                </div>
                
                    {/* </Scene>
                </Controller> */}
            </main>
        </div>
    )
}
